### Arithmetic Operations with `array`s and Individual Numeric Values

# 7.7 `array` Operators
* `array` operators perform operations on **entire `array`s**. 
* Can perform arithmetic **between `array`s and scalar numeric values**, and **between `array`s of the same shape**.

In [1]:
import numpy as np

In [3]:
numbers = np.arange(1, 6)

In [4]:
numbers

array([1, 2, 3, 4, 5])

In [5]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [6]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [7]:
numbers  # numbers is unchanged by the arithmetic operators

array([1, 2, 3, 4, 5])

In [8]:
numbers += 10

In [9]:
numbers

array([11, 12, 13, 14, 15])

### Broadcasting 
* Arithmetic operations require as operands two `array`s of the **same size and shape**. 
* **`numbers * 2`** is equivalent to **`numbers * [2, 2, 2, 2, 2]`** for a 5-element array.
* Applying the operation to every element is called **broadcasting**. 
* Also can be applied between `array`s of different sizes and shapes, enabling some concise and powerful manipulations.

### Arithmetic Operations Between `array`s 
* Can perform arithmetic operations and augmented assignments between `array`s of the _same_ shape

In [11]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [12]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [13]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

### Comparing `array`s
* Can compare `array`s with individual values and with other `array`s
* Comparisons performed **element-wise**
* Produce `array`s of Boolean values in which each element’s `True` or `False` value indicates the comparison result

In [ ]:
numbers

In [14]:
numbers >= 13

array([False, False,  True,  True,  True])

In [15]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [16]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [17]:
numbers == numbers2

array([False, False, False, False, False])

In [18]:
numbers == numbers

array([ True,  True,  True,  True,  True])

------
&copy;1992&ndash;2020 by Pearson Education, Inc. All Rights Reserved. This content is based on Chapter 5 of the book [**Intro to Python for Computer Science and Data Science: Learning to Program with AI, Big Data and the Cloud**](https://amzn.to/2VvdnxE).

DISCLAIMER: The authors and publisher of this book have used their 
best efforts in preparing the book. These efforts include the 
development, research, and testing of the theories and programs 
to determine their effectiveness. The authors and publisher make 
no warranty of any kind, expressed or implied, with regard to these 
programs or to the documentation contained in these books. The authors 
and publisher shall not be liable in any event for incidental or 
consequential damages in connection with, or arising out of, the 
furnishing, performance, or use of these programs.                  