In [2]:
import torch
w = torch.tensor(3.0, requires_grad = True)
b = torch.tensor(1.0, requires_grad = True)


In [ ]:
def forward(x):
  y = w*x + b
  return y

In [ ]:
x = torch.tensor(2)
forward(x)

tensor(7., grad_fn=<AddBackward0>)

In [ ]:
x = torch.tensor([[4],[7]])
forward(x)

tensor([[13.],
        [22.]], grad_fn=<AddBackward0>)

In [3]:
from torch.nn import Linear

In [ ]:
torch.manual_seed(1) # we set a seed for generating randeom numbers, # we want to ensure the random values assigend to our weight and bias values are consistent, hence we set a sedd.
model = Linear(in_features = 1, out_features = 1) # for every prediction that we make using the lieanr model, for every output, there is a single input
print(model.bias, model.weight) # get the parameters of the linear model

# weight = 0.5153
# bias = -0.4414

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [ ]:
x = torch.tensor([2.0])
print (model(x))

tensor([0.5891], grad_fn=<AddBackward0>)


In [ ]:
x = torch.tensor([[2],[3.3]]) # the input can be more than 1
# for each input, we can get one output y
print (model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward0>)


**Customirze a Linear Model**

In [14]:
# define object orientated model initialization
import torch.nn as nn

class LR(nn.Module):
  # constructor
  # self represent the instance itself
  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)

  def forward(self, x):
    pred = self.linear(x)
    return pred

In [15]:
torch.manual_seed(1)
model = LR(1,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [16]:
x = torch.tensor([1.0])
print(model.forward(x))

tensor([0.0739], grad_fn=<AddBackward0>)


In [17]:
x = torch.tensor([[1.0],[2.0]]) # make two predictions based on two indepent variables. 
print(model.forward(x))

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)
