In [3]:
import torch
x= torch.arange(18).view(3,2,3)
# return 3 block, each block contain two rows and three columns

supporse this is a building with three floors, 


0    [ 0,  1,  2],
     [ 3,  4,  5]

1    [ 6,  7,  8],
     [ 9, 10, 11]   

2        [12, 13, 14],
         [15, 16, 17]

Within each floor, suppose it is a room, with rows and columns.

if we want to access number 17, it is on third floor, second row and third column. Since our index begin with 0, 

In [5]:
x [2, 1, 2]

tensor(17)

In [6]:
#how about aceess number of 10?
x [1,1,1]

tensor(10)

In [7]:
#what about slice elements? if we want to slice the whole second floor
x [1, 0:2, 0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [9]:
# since we select all the rows and columns, we can omit is using :
x [1, :, :]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [8]:
# only slice [6,7,8]

x [1, 0:1, 0:3]

tensor([[6, 7, 8]])

**matrix multiplication A*B** 

must ensure the column of matrix A equals to rows of matrix B

In [12]:
mat_a = torch.tensor ([0,3,5,5,5,2]).view(2,3)
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [13]:
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [14]:
mat_a @ mat_b

tensor([[ 29, -16],
        [ 38,   6]])